s = set()
n = input("Enter a number: ")
s.add(int(n))
n = input("Enter a number: ")
s.add(int(n))
n = input("Enter a number: ")
s.add(int(n))
n = input("Enter a number: ")
s.add(int(n))
n = input("Enter a number: ")
s.add(int(n))
n = input("Enter a number: ")
s.add(int(n))
n = input("Enter a number: ")
s.add(int(n))
n = input("Enter a number: ")
s.add(int(n))

print(f"The unique numbers entered are: {s}")
